//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by LQDetect.rc
//
#define IDR_KEY_ENTER                   99
#define IDD_LQDETECT_DIALOG             102
#define IDD_DIALOG_PARAMETER            103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PASSWORD             130
#define IDD_DIALOG_DETECT               131
#define IDD_DIALOG_TEST                 132
#define IDD_DIALOG_DEMARCATE            133
#define IDD_DIALOG_SETDISPLAY           134
#define IDD_DIALOG_OTHERPARAMETER       135
#define IDD_DIALOG_LIQUID               136
#define IDB_BITMAP_LOGO                 136
#define IDD_DIALOG_CONTAINER            137
#define IDD_DIALOG_SPLASH               138
#define IDD_DIALOG_OK                   139
#define IDD_DIALOG_OKCANCEL             140
#define IDD_DIALOG_GENERAL              141
#define IDC_COMBO_CHANNEL               1001
#define IDC_RADIO_SAMPLINGMETHOD1       1004
#define IDC_RADIO_SAMPLINGMETHOD2       1005
#define IDC_BUTTON_PARAMETER            1006
#define IDC_EDIT_PASSWORD               1007
#define IDC_COMBO_CONTAINER             1008
#define IDC_LIST_TESTVALUE              1009
#define IDC_LIST_DETECTVALUE            1010
#define IDC_STATIC_DRAW                 1011
#define IDC_COMBO_LIQUID                1012
#define IDC_BUTTON_DETECT               1013
#define IDC_BUTTON_TEST                 1014
#define IDC_BUTTON_DEMARCATE            1015
#define IDC_EDIT_TIMES                  1016
#define IDC_COMBO_SECOND                1017
#define IDC_BUTTON_START                1018
#define IDC_EDIT_ISSAFE                 1019
#define IDC_BUTTON_MANUAL_DETECT        1020
#define IDC_EDIT_VALUE                  1021
#define IDC_EDIT_VALUE1                 1022
#define IDC_EDIT_VALUE2                 1023
#define IDC_EDIT_VALUE3                 1024
#define IDC_EDIT_VALUE4                 1025
#define IDC_EDIT_VALUE5                 1026
#define IDC_EDIT_VALUE6                 1027
#define IDC_EDIT_VALUE7                 1028
#define IDC_EDIT_VALUE8                 1029
#define IDC_EDIT_VALUE9                 1030
#define IDC_EDIT_VALUE10                1031
#define IDC_EDIT_VALUE11                1032
#define IDC_EDIT_VALUE12                1033
#define IDC_EDIT_VALUE13                1034
#define IDC_EDIT_VALUE14                1035
#define IDC_EDIT_VALUE15                1036
#define IDC_EDIT_VALUE16                1037
#define IDC_EDIT_VALUE17                1038
#define IDC_EDIT_VALUE18                1039
#define IDC_EDIT_VALUE19                1040
#define IDC_EDIT_VALUE20                1041
#define IDC_LIST_SWATCH                 1042
#define IDC_BUTTON_DELETE_SWATCH        1043
#define IDC_RADIO_CHANNEL1              1044
#define IDC_RADIO_CHANNEL2              1045
#define IDC_BUTTON_AUTO_DETECT          1046
#define IDC_BUTTON_CONTAINER            1047
#define IDC_BUTTON_LIQUID               1048
#define IDC_BUTTON_UPDATE_SWATCH        1049
#define IDC_BUTTON_SWATCH_BROWSE        1050
#define IDC_BUTTON_SET_DISPLAY          1051
#define IDC_BUTTON_SET_PARAMETER        1052
#define IDC_BUTTON_SET_THRESHOLD        1053
#define IDC_EDIT_INFO                   1054
#define IDC_EDIT_OLDVALUE               1055
#define IDC_EDIT_OLDVALUE1              1056
#define IDC_EDIT_NEWVALUE               1057
#define IDC_EDIT_NEWVALUE1              1058
#define IDC_EDIT_RATIO                  1059
#define IDC_EDIT_RATIO1                 1060
#define IDC_EDIT_THRESHOLDBEGIN         1061
#define IDC_EDIT_OLDVALUE2              1062
#define IDC_EDIT_THRESHOLDEND           1063
#define IDC_EDIT_NEWVALUE2              1064
#define IDC_RADIO_SINGLESAMPLE          1065
#define IDC_RADIO_DRAWSS                1066
#define IDC_RADIO_MULTISAMPLE           1067
#define IDC_RADIO_DRAWMS                1068
#define IDC_RADIO_DRAWSM                1069
#define IDC_CHECK_DIS                   1070
#define IDC_BUTTON_DISPLAYALL           1071
#define IDC_BUTTON_HIDEALL              1072
#define IDC_EDIT_COUNTUP                1073
#define IDC_EDIT_COUNTDOWN              1074
#define IDC_BUTTON_SAVE_SWATCH_MODIFY   1075
#define IDC_EDIT_COUNTAVERAGE           1076
#define IDC_COMBO_CHANNELINTERFACE1     1077
#define IDC_COMBO_CHANNELINTERFACE2     1078
#define IDC_COMBO_SAMPLINGTIMES         1079
#define IDC_EDIT_RATIO2                 1080
#define IDC_SPIN_TBEGIN                 1081
#define IDC_SPIN_TEND                   1082
#define IDC_BUTTON_SAVE                 1083
#define IDC_BUTTON_DELETE_DETECT_VALUE  1084
#define IDC_BUTTON_DELETE_OTHER_PARAMETER 1085
#define IDC_BUTTON_DELETEALL_DETECT_VALUE 1086
#define IDC_BUTTON_OTHER_PARAMETER      1087
#define IDC_LIST_LIQUID                 1088
#define IDC_EDIT_ID                     1089
#define IDC_EDIT_NAME                   1090
#define IDC_COMBO_ISSAFE                1091
#define IDC_BUTTON_ADDNEW               1092
#define IDC_SPIN_SET_X_V                1093
#define IDC_SPIN_SET_X_A                1094
#define IDC_EDIT_X_V                    1095
#define IDC_EDIT_X_T                    1096
#define IDC_BUTTON_SAVE_SAMPLINGDATA    1097
#define IDC_BUTTON_LOAD_SAMPLINGDATA    1098
#define IDC_EDIT_X_A                    1099
#define IDC_BUTTON_READ_X               1100
#define IDC_BUTTON_SET_X                1101
#define IDC_EDIT_SET_X_V                1102
#define IDC_EDIT_SET_X_A                1103
#define IDC_BUTTON_WARM_UP              1104
#define IDC_EDIT_TEXT                   1105
#define IDC_BUTTON_CLEAR_TIMES          1105
#define IDC_LIST_SAMPLE                 1106
#define IDC_STATIC_LABELCOLOR           1107
#define IDC_BUTTON_COLOR_DIS            1108
#define IDC_STATIC_CONTAINER_SELECT     1109
#define IDC_BUTTON_PLASTIC              1110
#define IDC_BUTTON_ALUM                 1111
#define IDC_BUTTON_OTHERS               1112
#define IDC_EDIT_CONTAINER              1113
#define IDC_EDIT_MEASURE_VALUE          1114
#define IDC_BUTTON_MANAGE               1115
#define IDC_BUTTON_CAL                  1116
#define IDC_BUTTON_XRAY                 1118
#define IDC_EDIT_TEMP                   1119
#define IDC_STATIC_TEMP                 1120
#define IDC_BUTTON_RETURN               1122
#define IDC_EDIT_MEASURE_TIMES          1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
